kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  namespace: stars
  name: frontend-policy-ext
spec:
  podSelector:
    matchLabels:
      role: frontend
  ingress:
     - ports:
       - protocol: TCP
         port: 80